fuegianboy/PetVogueBackEnd

- api/index.js
- api/package-lock.json
- api/package.json
- api/src/app.js
- api/src/db.js
- api/src/routes/index.js
- package-lock.json
- package.json
Initiate backend Project 
npm init, npm install, index.js, app.js, bd.js, routes/index.js
> Initiate Backend Project

- api/index.js
- api/package-lock.json
- api/package.json
- api/src/app.js
- api/src/db.js
- api/src/routes/index.js
- package-lock.json
- package.json
First merge to main from develop. Initial backend state
> First merge to main

- api/src/models/MedicalRecords.js
- api/src/models/Orders.js
- api/src/models/Pets.js
- api/src/models/Products
- api/src/models/Reviews.js
- api/src/models/Services.js
- api/src/models/Users.js
Database Models created, 
just models, not relations in db.js
> addModelsToBackend

- api/package-lock.json
- api/package.json
- api/src/models/Services.js
- api/src/routes/ordersRoutes.js
Add Field petID to Service model.
Fix route error with Orders controller
> AddFieldPetToService

- api/src/controllers/users/deleteUsers.controller.js
- api/src/controllers/users/getUsers.controller.js
- api/src/routes/usersRoutes.js
Add Logic delete of Users Model.
fix getUsersControllers to serch using "include"
> AddDeleteUserController

- api/src/controllers/services/getServices.js
Add new filter to Service controller using petid field
> AddFilterPetService

- api/src/controllers/orders/deleteOrders.controllers.js
- api/src/controllers/orders/getOrders.controllers.js
- api/src/controllers/orders/updateOrders.controller.js
- api/src/controllers/product/deleteProduct.js
- api/src/routes/ordersRoutes.js
CRUD for Orders created.
Routes was created
> AddOrdersControllers

- api/package-lock.json
- api/package.json
- api/src/controllers/mailer/mailTo.js
- api/src/controllers/mailer/message.js
- api/src/controllers/mailer/sendEmail.js
- api/src/routes/index.js
- api/src/routes/mailerRoutes.js
> Add Mailer Endpoint

- api/src/controllers/services/getServices.js
- api/src/models/Services.js
petID Fielf deleted
animalType Field added
> AddServicesField

- api/src/controllers/orders/getOrders.controllers.js
getOrders controlled fixed, petID eliminated
> Fix get orders

- api/src/controllers/bookings/createBooking.js
- api/src/db.js
relations added and create Booking fixed
> Fix bookings post

- api/src/controllers/assets/deleteAsset.js
- api/src/controllers/assets/getAsset.js
- api/src/controllers/assets/restoreAsset.js
- api/src/controllers/assets/updateAsset.js
- api/src/routes/assetsRoutes.js
- api/src/routes/servicesRouter.js
Fixed asset controllers
routes to services and asset were changed to use post when get information.
> fixAssetControllers

- api/src/controllers/services/createService.js
fix Services to accept equal categories property at creation
> fixServices

- api/index.js
- api/src/controllers/product/postProduct.js
- api/src/models/Products.js
- api/src/utils/validations.js
fix validation and force: false
> fix Validations

- api/src/controllers/assets/getAsset.js
- api/src/controllers/bookings/getBooking.js
- api/src/controllers/orders/getOrders.controllers.js
- api/src/controllers/pets/getPets.js
- api/src/controllers/product/getProducts.js
- api/src/controllers/services/getServices.js
- api/src/controllers/users/getUsers.controller.js
Pagination was added in all get controllers
> addPagination

- api/src/controllers/users/createUsers.controller.js
- api/src/controllers/users/loginUsers.controller.js
- api/src/routes/usersRoutes.js
- package-lock.json
- package.json
Creo controlador para inicio de sesion y agrego libreria bcrypt para encriptar contraseñas
> Nuevo controlador para inicio de sesion

- api/src/controllers/product/getProducts.js
productID filter was added to controller
> Add filter to Products

- api/src/controllers/services/getServices.js
Filter name_filter was modified to accept any value
> ModifyNameFilterInServices

- api/src/controllers/users/createUsers.controller.js
- api/src/routes/usersRoutes.js
- api/src/utils/ValidateToken.js
se añadieron la proteccion de rutas
> Rutas protegidas

- api/src/controllers/product/getProducts.js
filter by description was added
order by name was added
> addProductsFilters

- api/src/controllers/mercadopago/createOrder.js
- api/src/controllers/mercadopago/mercadoPago.js
- api/src/routes/mercadopagoRoutes.js
> mercadoPagoTest

- api/src/controllers/users/loginUsers.controller.js
- api/src/controllers/users/registerUser.controller.js
- api/src/routes/usersRoutes.js
Algunos fixeos al registro con un nuevo controlador
> Register fix

- api/src/controllers/users/adminLogin.controller.js
- api/src/controllers/users/createUsers.controller.js
- api/src/controllers/users/registerUser.controller.js
- api/src/routes/usersRoutes.js
Agrego nuevo controlador para el login con admin, y agrego validaciones de status y systemRole
> Admin validations

- api/src/controllers/mailer/mailTo.js
- api/src/controllers/users/createUsers.controller.js
se le hizo el nodeMailer al registro.  envía un email al usuario cuando se registra.
> Email register
